# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImagesViewer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-14
        copyright            : (C) 2023 by Dewberry
        email                : asiddiqui@dewberry.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Abdul Raheem Siddiqui"
__date__ = "2023-07-14"
__copyright__ = "(C) 2023 by Dewberry"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImagesViewer class from file ImagesViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .images_viewer import ImagesViewerPlugin

    return ImagesViewerPlugin(iface)
